
###
POST http://localhost:3000/reset-password
content-type: application/json

{
    "email":"ppppppppp",
    "newPass":"999", 
    "code":1672267060015
}
###
POST http://localhost:3000/forgot-password
content-type: application/json

{
    "email":"ppppppppp"
}

###
POST http://localhost:3000/login
content-type: application/json

{
    "email":"ppppppppp",
    "pass":"999"
}

###
GET http://localhost:3000/user

###
GET http://localhost:3000/user

###
DELETE  http://localhost:3000/user/5

###
POST http://localhost:3000/user
content-type: application/json

{
    "email":"abcdefgh",
    "pass":"123456789"
}

###
PUT http://localhost:3000/user/6
content-type: application/json

{
    "email":"ppppppppp",
    "pass":"000000000000"
}